import numpy as np
import matplotlib.pyplot as plt
import network_helper
from models import Resistor, Voltage_Source, Current_Source, Capacitor, Inductor, Diode
from print_utils import format_num, format_array
from collections import defaultdict
from math import log, exp

def populate_b_current(component, b, mna_idx):
    #KCL defined to be sum of currents entering a node
    b[mna_idx[component.node1]] += component.current
    b[mna_idx[component.node2]] -= component.current

def populate_A_conductance(component, A, mna_idx):
    #current flowing into node1 through R as a result of the voltage at node 1
    A[mna_idx[component.node1]][mna_idx[component.node1]] -= 1/component.resistance 
    #current flowing into node1 through R as a result of node2
    A[mna_idx[component.node1]][mna_idx[component.node2]] += 1/component.resistance 
    #current flowing into node2 as a result of node1
    A[mna_idx[component.node2]][mna_idx[component.node1]] += 1/component.resistance 
    #current flowing into node2 through R as a result of node2
    A[mna_idx[component.node2]][mna_idx[component.node2]] -= 1/component.resistance 

def populate_A_voltage(component, A, mna_idx):

            A[mna_idx[component.node1]][mna_idx[component.name]] += 1
            A[mna_idx[component.node2]][mna_idx[component.name]] -= 1
            A[mna_idx[component.name]][mna_idx[component.node1]] -= 1
            A[mna_idx[component.name]][mna_idx[component.node2]] += 1

def populate(component_list, graph, num_nodes, num_eqs):

    A = np.zeros((num_eqs + 1,num_eqs + 1), dtype=float) #create extra dummy ground row/col to discard eqs

    b = np.zeros(num_eqs + 1)

    idx = num_nodes
    for component in component_list:
        if isinstance(component, Voltage_Source):
            b[idx] = component.voltage
            idx += 1
        
    mna_idx_to_node = ['0' for x in range(num_eqs)]
    mna_idx = {}
    idx = 0
    # map nodes to indicies on the A matrix
    for node in graph:
        if node == '0':
            mna_idx[node] = num_eqs
        else:
            mna_idx[node] = idx
            mna_idx_to_node[idx] = node
            idx += 1

    for component in component_list:
        if isinstance(component, Voltage_Source):
            mna_idx[component.name] = idx
            mna_idx_to_node[idx] = component.name
            idx += 1

    for component in component_list:
        if isinstance(component, Capacitor) or isinstance(component, Inductor):
            populate_b_current(component.i_norton,b,mna_idx)
            populate_A_conductance(component.r_norton,A,mna_idx)

        if isinstance(component, Diode):
            component.compute_norton()
            populate_b_current(component.i_norton,b,mna_idx)
            populate_A_conductance(component.r_norton,A,mna_idx)

        if isinstance(component, Current_Source):
            populate_b_current(component, b, mna_idx)

        # populate conductivity matrix
        if isinstance(component, Resistor):
            populate_A_conductance(component, A, mna_idx)

        # finish KCL with currents flowing from voltage source
        elif isinstance(component, Voltage_Source):
            # we have defined the current as flowing from the pos term towards negative
            print(component.node1, component.node2, "=", format_num(component.voltage))
            populate_A_voltage(component, A, mna_idx)
    
    return (A,b,mna_idx,mna_idx_to_node)

def update_diode(mna_idx, diode, z):

    z_grounded = np.pad(z, (0, 1), mode='constant')
    diode.voltage = z_grounded[mna_idx[diode.node1]] - z_grounded[mna_idx[diode.node2]]
    error = diode.voltage-diode.v_guess
    print(f"We calculate {format_num(diode.voltage)} volts across diode {diode.name} after pass 1. initial guess was {format_num(diode.v_guess)}. Error: {format_num(error)}")
    diode.v_guess = max(diode.v_guess - diode.v_change_max, min(diode.v_guess+diode.v_change_max, diode.voltage))
    return error


#solves for the operating point of a circuit
def MNA(graph, component_list, non_linear = False, tolerance = 0.01):
    #uses the form Ax = b where A is a matrix generated by KCL at each node combined with KVL for each voltage source

    for i, component in enumerate(component_list):
        if isinstance(component, Capacitor):
            component_list[i] = Resistor(
                component.node1,
                component.node2,
                1e300,
                component.name
            )

        elif isinstance(component, Inductor):
            component_list[i] = Resistor(
                component.node1,
                component.node2,
                1e-300,
                component.name
            )

    # create skeleton for A (size of #nodes - 1 + #voltages)
    num_nodes = network_helper.num_nodes(graph)
    num_eqs = network_helper.count_voltages(component_list)
    num_eqs += num_nodes


    # solve system of equations
    loops = 0
    if(non_linear): #TODO loop runs one extra time
        #find predicted voltage across caps
        while(True):
            error = tolerance + 1
            diode = None
            for component in component_list:
                if(isinstance(component,Diode)):
                    diode = component
                    if(loops > 0):
                        error = update_diode(mna_idx, component, z)
                    component.compute_norton()

            A,b,mna_idx, mna_idx_to_node = populate(component_list, graph, num_nodes, num_eqs)
            
            print("eq b =", format_array(b))
            print("A =", format_array(A))
            
            A_no_ground = A[0:-1, 0:-1] 
            b_no_ground = b[0:-1]
            z = np.linalg.solve(A_no_ground,b_no_ground)

            print(f"\n\nLoop number {loops}:")
            print(f"Diode internals used: Resistance{format_num(diode.r_norton.resistance)}, Current: {format_num(diode.i_norton.current)}")
            for i in range(num_nodes):
                print("Voltage at node:", mna_idx_to_node[i], "=", format_num(z[i]))

            for i in range(num_nodes, num_eqs):
                print("Current through Voltage Source:", mna_idx_to_node[i], "=", format_num(z[i]))

            if(error < tolerance or loops > 10):
                break

            loops += 1
            
    EPS = 1e-12

    for i in range(num_nodes):
        value = 0.0 if abs(z[i]) < EPS else z[i]
        print("Voltage at node:", mna_idx_to_node[i], "=", f"{value:.2e}")

    for i in range(num_nodes, num_eqs):
        value = 0.0 if abs(z[i]) < EPS else z[i]
        print("Current through Voltage Source:", mna_idx_to_node[i], "=", f"{value:.2e}")

#Extending MNA to time varying circuits?
def MNA_time(graph, component_list, dt = 0.01, end_time = 1, plot_voltage = True):
    #uses the form Ax = b where A is a matrix generated by KCL at each node combined with KVL for each voltage source

    # initialize capacitors/inductors for simulation
    for component in component_list:
        if isinstance(component, Capacitor) or isinstance(component, Inductor):
            component.init_norton(dt)

    # create skeleton for A (size of #nodes - 1 + #voltages)
    num_nodes = network_helper.num_nodes(graph)
    num_eqs = network_helper.count_voltages(component_list)
    num_eqs += num_nodes

    #create a node translation table between the user given names and the idx of the matrix
    mna_idx_to_node = ['0' for x in range(num_eqs)]
    mna_idx = {}
    idx = 0

    # map nodes to indicies on the A matrix
    for node in graph:
        if node == '0':
            mna_idx[node] = num_eqs
        else:
            mna_idx[node] = idx
            mna_idx_to_node[idx] = node
            idx += 1
 
    # map voltages to indicies on the matrix
    for component in component_list:
        if isinstance(component, Voltage_Source):
            mna_idx[component.name] = idx
            mna_idx_to_node[idx] = component.name
            idx += 1

    
    time = 0
    voltage_history = defaultdict(list)
    while(time < end_time):
        A = np.zeros((num_eqs + 1,num_eqs + 1), dtype=float) #create extra dummy ground row/col to discard eqs
        b = np.zeros(num_eqs + 1)
        # Generate RHS
        for component in component_list:
            if isinstance(component, Voltage_Source):
                # Explicitly look up the correct matrix row using your index dictionary
                target_idx = mna_idx[component.name]
                b[target_idx] = component.voltage
        """
        # Generate RHS
        idx = num_nodes
        for component in component_list:
            if isinstance(component, Voltage_Source):
                b[idx] = component.voltage
                idx += 1
        """
        # We will be using KCL and always assuming that all currents are flowing into each node st their sum is 0
        for component in component_list:
            #populate current list
            if isinstance(component, Capacitor) or isinstance(component, Inductor):
                populate_b_current(component.i_norton,b,mna_idx)
                populate_A_conductance(component.r_norton,A,mna_idx)
            if isinstance(component, Current_Source):
                # if current is positive -> flowing from node1 into node2, so we should add to eq for node 1 and subtract from eq for node2
                populate_b_current(component,b,mna_idx)
            # populate conductivity matrix
            if isinstance(component, Resistor):
                populate_A_conductance(component, A, mna_idx)

            # finish KCL with currents flowing from voltage source
            elif isinstance(component, Voltage_Source):
                # we have defined the current as flowing from the pos term towards negative
                populate_A_voltage(component,A,mna_idx)

        A = A[0:-1, 0:-1] 
        b = b[0:-1]
        #print("eq b = ",b)

        #print(A)

        # solve system of equations
        z = np.linalg.solve(A,b)
        #print(z)

        node_to_voltage = {}
        node_to_voltage['0'] = 0

        #Find voltage at all nodes
        for i in range(num_nodes):
            node = mna_idx_to_node[i]
            voltage = z[i]
            node_to_voltage[node] = voltage
            voltage_history[node].append(voltage)

        #find the voltage across capacitors:
        for component in component_list:
            if(isinstance(component, Capacitor)):
                #breakpoint()
                #update norton equivalent circuit for the capacitor
                # C = Q/V
                # C * dV/dt = I
                # V'(t) = 1/C * I
                # V(t+dt) = V(t) + 1/C * I * dt
                # determine norton equivalent current with I SC
                # if V(t+dt) = 0
                # I = -V(t) * C/dt
                component.i_norton.current = (node_to_voltage[component.node1] - node_to_voltage[component.node2]) * component.capacitance/dt
                # determine current through voltage source:
            elif(isinstance(component, Inductor)):

                Vl = (node_to_voltage[component.node1] - node_to_voltage[component.node2])
                component.i_norton.current =  -Vl * dt / component.inductance + component.i_norton.current 
        
        #for i in range(num_nodes, num_eqs):
            #print("Current through Voltage Source:", mna_idx_to_node[i], "=",z[i])
        
        time += dt

    # Plot every node voltage over time before returning
    if voltage_history and plot_voltage:
        num_steps = len(next(iter(voltage_history.values())))
        time_axis = np.arange(num_steps) * dt

        plt.figure(figsize=(10, 6))
        for node, history in voltage_history.items():
            plt.plot(time_axis, history, label=node, linewidth=2)

        plt.xlabel('Time (s)')
        plt.ylabel('Voltage (V)')
        plt.title('Node Voltages Over Time')
        plt.legend()
        plt.grid(True)
        plt.tight_layout()
        plt.show()

    return voltage_history
