import numpy as np
import matplotlib.pyplot as plt
import network_helper
from models import Resistor, Voltage_Source, Current_Source, Capacitor, Inductor
from collections import defaultdict

# solves the circuit at a given time
def MNA(graph, component_list):
    #uses the form Ax = b where A is a matrix generated by KCL at each node combined with KVL for each voltage source

    # create skeleton for A (size of #nodes - 1 + #voltages)
    num_nodes = network_helper.num_nodes(graph)
    num_eqs = network_helper.count_voltages(component_list)
    num_eqs += num_nodes

    A = np.zeros((num_eqs + 1,num_eqs + 1), dtype=float) #create extra dummy ground row/col to discard eqs

    b = np.zeros(num_eqs + 1)

    # Generate RHS
    idx = num_nodes
    for component in component_list:

        if isinstance(component, Voltage_Source):
            b[idx] = component.voltage
            idx += 1
        
    

    #create a node translation table between the user given names and the idx of the matrix
    mna_idx_to_node = ['0' for x in range(num_eqs)]
    mna_idx = {}
    idx = 0
    # map nodes to indicies on the A matrix
    for node in graph:
        if node == '0':
            mna_idx[node] = num_eqs
        else:
            mna_idx[node] = idx
            mna_idx_to_node[idx] = node
            idx += 1
    
    # map voltages to indicies on the matrix
    for component in component_list:
        if isinstance(component, Voltage_Source):
            mna_idx[component.name] = idx
            mna_idx_to_node[idx] = component.name
            idx += 1


    # We will be using KCL and always assuming that all currents are flowing into each node st their sum is 0

    for component in component_list:

        if isinstance(component, Current_Source):
            # if current is positive -> flowing from node1 into node2, so we should add to eq for node 1 and subtract from eq for node2
            if component.current > 0:
                b[mna_idx[component.node1]] -= component.current
                b[mna_idx[component.node2]] += component.current
            else:
                b[mna_idx[component.node1]] += component.current
                b[mna_idx[component.node2]] -= component.current

        # populate conductivity matrix
        if isinstance(component, Resistor):
            #current flowing into node1 through R as a result of the voltage at node 1
            A[mna_idx[component.node1]][mna_idx[component.node1]] -= 1/component.resistance 
            #current flowing into node1 through R as a result of node2
            A[mna_idx[component.node1]][mna_idx[component.node2]] += 1/component.resistance 
            #current flowing into node2 as a result of node1
            A[mna_idx[component.node2]][mna_idx[component.node1]] += 1/component.resistance 
            #current flowing into node2 through R as a result of node2
            A[mna_idx[component.node2]][mna_idx[component.node2]] -= 1/component.resistance 
        # finish KCL with currents flowing from voltage source
        elif isinstance(component, Voltage_Source):
            # we have defined the current as flowing from the pos term towards negative
            print(component.node1, component.node2, component.voltage)
            if(component.voltage > 0):
                A[mna_idx[component.node1]][mna_idx[component.name]] += 1
                A[mna_idx[component.node2]][mna_idx[component.name]] -= 1
                A[mna_idx[component.name]][mna_idx[component.node1]] -= 1
                A[mna_idx[component.name]][mna_idx[component.node2]] += 1
            else:
                A[mna_idx[component.node1]][mna_idx[component.name]] -= 1
                A[mna_idx[component.node2]][mna_idx[component.name]] += 1
                A[mna_idx[component.name]][mna_idx[component.node1]] += 1
                A[mna_idx[component.name]][mna_idx[component.node2]] -= 1


    A = A[0:-1, 0:-1] 
    b = b[0:-1]
    print("eq b = ",b)

    print(A)

    # solve system of equations
    z = np.linalg.solve(A,b)
    print(z)

    for i in range(num_nodes):
        print("Voltage at node:", mna_idx_to_node[i], "=",z[i])
    
    for i in range(num_nodes, num_eqs):
        print("Current through Voltage Source:", mna_idx_to_node[i], "=",z[i])

def populate_b_current(component, b, mna_idx):
    #if component.current > 0:
    b[mna_idx[component.node1]] -= component.current
    b[mna_idx[component.node2]] += component.current
    """
    else:
        b[mna_idx[component.node1]] += component.current
        b[mna_idx[component.node2]] -= component.current
        """

def populate_A_conductance(component, A, mna_idx):
    #current flowing into node1 through R as a result of the voltage at node 1
    A[mna_idx[component.node1]][mna_idx[component.node1]] -= 1/component.resistance 
    #current flowing into node1 through R as a result of node2
    A[mna_idx[component.node1]][mna_idx[component.node2]] += 1/component.resistance 
    #current flowing into node2 as a result of node1
    A[mna_idx[component.node2]][mna_idx[component.node1]] += 1/component.resistance 
    #current flowing into node2 through R as a result of node2
    A[mna_idx[component.node2]][mna_idx[component.node2]] -= 1/component.resistance 

def populate_A_voltage(component, A, mna_idx):
            #if(component.voltage > 0): #TODO temp change
            A[mna_idx[component.node1]][mna_idx[component.name]] += 1
            A[mna_idx[component.node2]][mna_idx[component.name]] -= 1
            A[mna_idx[component.name]][mna_idx[component.node1]] -= 1
            A[mna_idx[component.name]][mna_idx[component.node2]] += 1
            """
            else:
                A[mna_idx[component.node1]][mna_idx[component.name]] -= 1
                A[mna_idx[component.node2]][mna_idx[component.name]] += 1
                A[mna_idx[component.name]][mna_idx[component.node1]] += 1
                A[mna_idx[component.name]][mna_idx[component.node2]] -= 1
            """
#Extending MNA to time varying circuits?
def MNA_time(graph, component_list, dt = 0.01, end_time = 1, plot_voltage = True):
    #uses the form Ax = b where A is a matrix generated by KCL at each node combined with KVL for each voltage source

    # initialize capacitors/inductors for simulation
    for component in component_list:
        if isinstance(component, Capacitor) or isinstance(component, Inductor):
            component.init_norton(dt)

    # create skeleton for A (size of #nodes - 1 + #voltages)
    num_nodes = network_helper.num_nodes(graph)
    num_eqs = network_helper.count_voltages(component_list)
    num_eqs += num_nodes

    #create a node translation table between the user given names and the idx of the matrix
    mna_idx_to_node = ['0' for x in range(num_eqs)]
    mna_idx = {}
    idx = 0

    # map nodes to indicies on the A matrix
    for node in graph:
        if node == '0':
            mna_idx[node] = num_eqs
        else:
            mna_idx[node] = idx
            mna_idx_to_node[idx] = node
            idx += 1
 
    # map voltages to indicies on the matrix
    for component in component_list:
        if isinstance(component, Voltage_Source):
            mna_idx[component.name] = idx
            mna_idx_to_node[idx] = component.name
            idx += 1

    
    time = 0
    voltage_history = defaultdict(list)
    while(time < end_time):
        A = np.zeros((num_eqs + 1,num_eqs + 1), dtype=float) #create extra dummy ground row/col to discard eqs
        b = np.zeros(num_eqs + 1)
        # Generate RHS
        for component in component_list:
            if isinstance(component, Voltage_Source):
                # Explicitly look up the correct matrix row using your index dictionary
                target_idx = mna_idx[component.name]
                b[target_idx] = component.voltage
        """
        # Generate RHS
        idx = num_nodes
        for component in component_list:
            if isinstance(component, Voltage_Source):
                b[idx] = component.voltage
                idx += 1
        """
        # We will be using KCL and always assuming that all currents are flowing into each node st their sum is 0
        for component in component_list:
            #populate current list
            if isinstance(component, Capacitor) or isinstance(component, Inductor):
                populate_b_current(component.i_norton,b,mna_idx)
                populate_A_conductance(component.r_norton,A,mna_idx)
            if isinstance(component, Current_Source):
                # if current is positive -> flowing from node1 into node2, so we should add to eq for node 1 and subtract from eq for node2
                populate_b_current(component,b,mna_idx)
            # populate conductivity matrix
            if isinstance(component, Resistor):
                populate_A_conductance(component, A, mna_idx)

            # finish KCL with currents flowing from voltage source
            elif isinstance(component, Voltage_Source):
                # we have defined the current as flowing from the pos term towards negative
                populate_A_voltage(component,A,mna_idx)

        A = A[0:-1, 0:-1] 
        b = b[0:-1]
        #print("eq b = ",b)

        #print(A)

        # solve system of equations
        z = np.linalg.solve(A,b)
        #print(z)

        node_to_voltage = {}
        node_to_voltage['0'] = 0

        #Find voltage at all nodes
        for i in range(num_nodes):
            node = mna_idx_to_node[i]
            voltage = z[i]
            node_to_voltage[node] = voltage
            voltage_history[node].append(voltage)

        #find the voltage across capacitors:
        for component in component_list:
            if(isinstance(component, Capacitor)):
                #breakpoint()
                #update norton equivalent circuit for the capacitor
                # C = Q/V
                # C * dV/dt = I
                # V'(t) = 1/C * I
                # V(t+dt) = V(t) + 1/C * I * dt
                # determine norton equivalent current with I SC
                # if V(t+dt) = 0
                # I = -V(t) * C/dt
                component.i_norton.current = (node_to_voltage[component.node1] - node_to_voltage[component.node2]) * component.capacitance/dt
                # determine current through voltage source:
            elif(isinstance(component, Inductor)):

                Vl = (node_to_voltage[component.node1] - node_to_voltage[component.node2])
                component.i_norton.current =  -Vl * dt / component.inductance + component.i_norton.current 
        
        #for i in range(num_nodes, num_eqs):
            #print("Current through Voltage Source:", mna_idx_to_node[i], "=",z[i])
        
        time += dt

    # Plot every node voltage over time before returning
    if voltage_history and plot_voltage:
        num_steps = len(next(iter(voltage_history.values())))
        time_axis = np.arange(num_steps) * dt

        plt.figure(figsize=(10, 6))
        for node, history in voltage_history.items():
            plt.plot(time_axis, history, label=node, linewidth=2)

        plt.xlabel('Time (s)')
        plt.ylabel('Voltage (V)')
        plt.title('Node Voltages Over Time')
        plt.legend()
        plt.grid(True)
        plt.tight_layout()
        plt.show()

    return voltage_history
